version: '2'
services:
    race-app:
        image: race
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://race-postgresql:5432/race
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8686:8686
    race-postgresql:
        extends:
            file: postgresql.yml
            service: race-postgresql
